apiVersion: v1
kind: Service
metadata:
  labels:
      app: nginx-deploy
  name: nginx-svc
spec:
  ports:
  - port: 80
    nodePort: 32625
    targetPort: 80
    protocol: TCP    
  selector:
    app: nginx-deploy
  type: NodePort

